name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Client
        run: |
          echo "::warning file=action.yml,line=1,col=5,endColumn=7::Missing semicolon"
